from retrieval.engines.bm25 import build_bm25_index
from retrieval.structure.filters import filter_spans_by_section_priors
from schemas.internal.documents import SectionSpan


def test_structure_filter_reduces_noise_sections() -> None:
    spans = [
        SectionSpan(
            paragraph_id="p1",
            title="Methods",
            page=1,
            text="We used a randomization sequence generated by computer.",
        ),
        SectionSpan(
            paragraph_id="p2",
            title="Discussion",
            page=5,
            text="randomization " * 20,
        ),
    ]

    full_index = build_bm25_index(spans)
    full_hits = full_index.search("randomization", top_n=2)
    assert full_hits
    assert full_hits[0].doc_index == 1

    filtered = filter_spans_by_section_priors(spans, ["methods"])
    assert filtered.indices == [0]

    structured_index = build_bm25_index([spans[i] for i in filtered.indices])
    structured_hits = structured_index.search("randomization", top_n=2)
    assert structured_hits
    assert structured_hits[0].doc_index == 0

